### ISSUE TITLE
Installing latest from pypi fails

### ISSUE THREAD

**Issue by niboowin** [alexpulver/cdk-chalice#16]
Unable to install the most recent version **0.7.0** from pypi. 

```sh
docker run --rm -it python:3.8-slim bash -c "pip install cdk-chalice"
```
```log
Collecting cdk-chalice
  Downloading cdk-chalice-0.7.0.tar.gz (5.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-393xkuve/cdk-chalice/setup.py'"'"'; __file__='"'"'/tmp/pip-install-393xkuve/cdk-chalice/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4wg6jrir
         cwd: /tmp/pip-install-393xkuve/cdk-chalice/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-393xkuve/cdk-chalice/setup.py", line 9, in <module>
        with open(os.path.join(here, 'about.py'), 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-393xkuve/cdk-chalice/about.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Was successful when referencing the git repo directly via:

```sh
pip install git+https://github.com/alexpulver/cdk-chalice.git
```

**Comment by alexpulver** [comment]
@niboowin thanks for reporting the issue! I could reproduce it, working on a fix
