### ISSUE TITLE
JSII Runtime Error

### ISSUE THREAD

**Issue by meleksomai** [alexpulver/cdk-chalice#9]
Hi,

I am building an example following the tutorial (https://aws.amazon.com/blogs/developer/deploying-aws-chalice-application-using-aws-cloud-development-kit/). 

I am using the following Python packages

```
aws_cdk.aws_dynamodb==1.19.0
aws_cdk.core==1.20.0
cdk-chalice==0.6.1
jsii==1.0.0
```

However, when running the `cdk synth`, I get the error below. When I remove `self.chalice=Chalice(self, 'AccountApi', source_dir=account_api_source_dir, stage_config=chalice_stage_config)` from the stack, the `cdk synth` compiles properly. 

```
(node:4088) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
Packaging Chalice app for AccountApiDev
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    AccountApi(app, 'AccountApiDev', env=dev_env)
  File "~/.virtualenvs/devops/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "~/workspace/InceptionHealth/eligibility_api/devops/stacks/account_api.py", line 44, in __init__
    stage_config=chalice_stage_config)
  File "~/.virtualenvs/devops/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "~/.virtualenvs/devops/lib/python3.7/site-packages/cdk_chalice.py", line 103, in __init__
    self.sam_package_dir = self._package_app()
  File "~/.virtualenvs/devops/lib/python3.7/site-packages/cdk_chalice.py", line 129, in _package_app
    self._package_app_subprocess(sam_package_dir)
  File "~/.virtualenvs/devops/lib/python3.7/site-packages/cdk_chalice.py", line 165, in _package_app_subprocess
    subprocess.run(command, cwd=self.source_dir, env=self.package_config.env)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/local/opt/python/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 810, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Subprocess exited with error 1

```

Any fix?

Thanks!

**Comment by alexpulver** [comment]
Hi @meleksomai , thanks for reporting the issue!

Can you please add the following snippet right before creating instance of `Chalice` class, and paste the output?
```python
import shutil
print(f'Path to Chalice executable is: {shutil.which('chalice')}')
```
When packaging a Chalice app using the default subprocess mode, `cdk-chalice` tries to locate the `chalice` executable for running `chalice package` command, and based on the traceback it seems that it cannot find the executable after the lookup.
